coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no